### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ftomassetti** [davidmoreno/onion#103]
Hi, I am not sure which License is used: LGPL or APACHE?

**Comment by davidmoreno** [comment]
As LICENSE.txt explains:

Contents of the src folder (the Library) is licensed under both GPLv2+ and Apache 2. See APACHE2.txt and GPLv2.txt files for more details.

All the rest of the code (examples, tests, tools) are AGPLv3. See AGPL.txt file for details.

The GPLv2+ compatibility is needed as Apache 2 is not compatible with GPLv2: http://www.gnu.org/licenses/license-list.html#apache2
