### ISSUE TITLE
C++11 memory issue 

### ISSUE THREAD

**Issue by bstarynk** [davidmoreno/onion#105]
See https://groups.google.com/a/coralbits.com/d/msg/onion-dev/_m1I-u_b18M/uJQ7SLRFEg8J

```C++
// file testonion.cc
#include <iostream>
#include <string>
#include "onion/onion.hpp"
#include "onion/response.hpp"
#include "onion/url.hpp"
#include "onion/shortcuts.hpp"

void ya_web_service(int port)
{
  Onion::Onion onionserver(O_THREADED);
  onionserver.setPort(port);
  Onion::Url onionrooturl(&onionserver);
  Onion::ExportLocal onionlocalwebdir("webdir");
  onionrooturl.add("^webdir/", onionlocalwebdir);
  std::cout << "Ya web service on port " << port << std::endl;
  onionserver.listen();
}

int main (int argc, char** argv)
{
  int portnum = (argc>1) ? std::stoi(argv[1]):8080;
  ya_web_service(portnum);
  std::cout << "end of main" << std::endl;
  return 0;
}
``` 

Compile it as `cd ~/tmp/; g++ -std=c++11 -Wall -g -I /usr/local testonion.cc -o testonion -L/usr/local -lonioncpp -lonion`

then run it in a directory having a `webdir/` subdirectory having some `webdir/index.html` file.

libonion is master, commit 25d4a2ad8cb6bd4e193ba69589fe7ad8674c2f57

**Comment by davidmoreno** [comment]
After many hours I have something functional on the cppnext branch. If you think this solves your problem, close this issue and I will merge all to master. NEEDS TESTING. BREAKS API.

Now Onion::Handler can not be copied, it can only be moved. This makes ownership easier to reason about. 

Also I added two really helpful functions: `onion_handler_c_to_cpp` and `onion_handler_cpp_to_c`. They convert from `onion_handler *` (c) to `Onion::Handler` (c++) and vice versa.

Almost all original handlers had to be converted, and this may mean custom handlers need to be converted too. First I created a HandlerBase from which handlers should inherit, and a Handler that contains a unique_ptr to a HandlerBase. This is needed to ensure ownership rules; I need a std::unique_ptr<HandlerBase>, and writing all the time that is error prone. Also lack of std::make_unique at C++11 does not help. As a side effect custom handlers can be automatically converted from pointers to Handler, and it becomes a managed HandlerBase. There is also a Handler::make<T>(...) similar to std::make_shared<T>(...). 

Also I removed many superficial classes that were wrappers for C handlers, and used the mentioned `onion_handler_c_to_cpp`. 

The conflictive part of your code is now part of a convoluted but functional test at [tests/08-cpp/03-urls.cpp](https://github.com/davidmoreno/onion/blob/cppnext/tests/08-cpp/03-urls.cpp#L75-L76)

After all this refactoring data should be easier to understand, and a bit faster, as there was an implicit C `onion_handler *` for each C++ Handler class which may be just more steps. On this regard Onion::Url can be optimized to do all using just C++, but might require a C++ reimplementation.

Feel free to do pull requests, as always.

Regards,
David.

**Comment by bstarynk** [comment]
On 03/19/2015 08:49 PM, David Moreno Montero wrote:
>
> After many hours I have something functional on the cppnext branch. If 
> you think this solves your problem, close this issue and I will merge 
> all to master. NEEDS TESTING. BREAKS API.
>

I trust you, because the failing example was the only thing I wrote in 
C++ for onion and it crashed immediately. In other words, I have never 
been able to use the C++ onion (since my first and only trial failed, 
and was the issue #105.

I'm not sure you have many C++ users (since I guess they would have 
found the #105 bug as quickly as I did).

So it is not a big trouble to change the C++ API. However, you might 
consider making a new release soon. I'll be delighted to be able to 
query the version programmatically (but I can manage without).


When buiding with clang 3.5 (on Debian/Sid/x86-64) I have the following 
warnings:
[ 18%] Building C object src/onion/CMakeFiles/onion_static.dir/https.c.o
cd /usr/src/Libs/onion/build/src/onion && /usr/bin/clang -DHAVE_GNUTLS 
-DHAVE_PAM -DHAVE_PTHREADS -DHAVE_SQLITE3 -DHAVE_WEBDAV -DJPEG_ENABLED 
-DONION_VERSION=\"0.7.git157.25d4a\" -DPNG_ENABLED -D_BSD_SOURCE 
-D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112L -Wall -O2 -fPIC -g -O 
-I/usr/src/Libs/onion/src -I/usr/include/libxml2    -o 
CMakeFiles/onion_static.dir/https.c.o   -c 
/usr/src/Libs/onion/src/onion/https.c
/usr/src/Libs/onion/src/onion/https.c:41:1: warning: 'gcry_thread_cbs' 
is deprecated [-Wdeprecated-declarations]
GCRY_THREAD_OPTION_PTHREAD_IMPL;
^
/usr/include/gcrypt.h:225:17: note: expanded from macro 
'GCRY_THREAD_OPTION_PTHREAD_IMPL'
--
/usr/include/gcrypt.h:211:8: note: 'gcry_thread_cbs' has been explicitly 
marked deprecated here
struct gcry_thread_cbs
        ^
1 warning generated.


Hope that will help. Thanks for the bug fixing. Hope to see it in master 
ASAP!

Cheers

-- 
Basile STARYNKEVITCH         http://starynkevitch.net/Basile/
email: basile<at>starynkevitch<dot>net mobile: +33 6 8501 2359
8, rue de la Faiencerie, 92340 Bourg La Reine, France
*** opinions {are only mine, sont seulement les miennes} ***

**Comment by davidmoreno** [comment]
I close dthe issue as I merged cppnext into master. For the other part, the gcry_thread_cbs I will work on it.
