### ISSUE TITLE
How to send an empty response?

### ISSUE THREAD

**Issue by surdocteam** [davidmoreno/onion#106]
When user downloads a empty file, the response should be empty, but onion will send nothing to client,
if tested with curl, curl will print "Server returned nothing (no headers, no data)".

I tried ::onion_response_set_length(resp, 0), but not work.

**Comment by surdocteam** [comment]
onion_response_flush() will not send headers if handler writes nothing to it, I think this should be problem to fix.

**Comment by davidmoreno** [comment]
Just now it needs at lease to call `onion_response_write_headers(response)`, but maybe this should not be mandatory, as its not possible to know always in advance if the response will be empty.

Setting the onion_response_set_length(res, 0) is good idea anyway to ensure the keep alive, before writing the headers.

I will try to enforce sending at least the headers in the response code path, without need to call this function explicitly.
