### ISSUE TITLE
onion_html_quote buggy

### ISSUE THREAD

**Issue by bstarynk** [davidmoreno/onion#108]
with the latest commit, i.e. c812b354a5923dea21fa049dfd423be54758ba51
   `onion_html_quote("/foo?xx=1&yy=2")` gives `NULL`  but should return an allocated string containing
`"/foo?xx=1&amp;yy=2"`

**Comment by davidmoreno** [comment]
It's fixed, but Im not sure if onion_html_quote behaviour is very nice. If you feel it should be improved, please reopen the bug or open another.

Currently it returns NULL if the string does not need to be encoded. This means the caller has to check the return value and use that, or use the original string. The rationale is to prevent a malloc, but maybe its worse on the API level.

**Comment by bstarynk** [comment]
You could consider providing another function which always return a `malloc`-ed string. Something like

      // always return a freshly allocated string which should later be `onion_low_free`-d ...
      // .... by calling code
      const char* onion_duped_html_quote(const char* str) {
         if (!str) return NULL;
         const char* quostr = onion_html_quote(str);
         if (!quostr) return onion_low_strdup(str);
         else return quostr;
      }

**Comment by davidmoreno** [comment]
Sounds good. Only I would prefer onion_html_quote_dup.

Do you mind preparing a Pull Request?

2015-07-23 11:04 GMT+02:00 Basile Starynkevitch <notifications@github.com>:

> You could consider providing another function which always return a malloc-ed
> string. Something like
>
>   // always return a freshly allocated string which should later be `onion_low_free`-d ...
>   // .... by calling code
>   const char* onion_duped_html_quote(const char* str) {
>      if (!str) return NULL;
>      const char* quostr = onion_html_quote(str);
>      if (!quostr) return onion_low_strdup(str);
>      else return quostr;
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidmoreno/onion/issues/108#issuecomment-124027487>.
>



-- 
David Moreno Montero

dmoreno@coralbits.com
+34 658 18 77 17
<http://www.coralbits.com/>
http://www.coralbits.com

**Comment by bstarynk** [comment]
On 07/23/2015 12:40, David Moreno Montero wrote:
> Sounds good. Only I would prefer onion_html_quote_dup.
>
> Do you mind preparing a Pull Request?

Done.

https://github.com/davidmoreno/onion/pull/113

-- 
Basile STARYNKEVITCH         http://starynkevitch.net/Basile/
email: basile<at>starynkevitch<dot>net mobile: +33 6 8501 2359
8, rue de la Faiencerie, 92340 Bourg La Reine, France
*** opinions {are only mine, sont seulement les miennes} ***
