### ISSUE TITLE
HTTP return codes

### ISSUE THREAD

**Issue by fredrikwidlund** [davidmoreno/onion#111]
As I understand it HTTP return codes should be as specified by RFC 7231 (http://tools.ietf.org/html/rfc7231#section-6.5.12), "Not Found" instead "NOT FOUND", etc.

i.e.
case HTTP_NOT_FOUND:
return "NOT FOUND";
..
should be
case HTTP_NOT_FOUND:
return "Not Found";

and so forth for all codes.

**Comment by davidmoreno** [comment]
Not sure if its really important, but it does not hurt for sure.

**Comment by fredrikwidlund** [comment]
Though "200" is actually just "OK", not "Ok". (Which you changed it to)

Probably doesn't break anything so not important in that way, but still its nice to be compliant.
