### ISSUE TITLE
returning OCS_NOT_IMPLEMENTED results in html body with typo

### ISSUE THREAD

**Issue by fredrikwidlund** [davidmoreno/onion#112]
Below should be 501 - ..., not 505 - ...

<pre>
HTTP/1.1 501 NOT IMPLEMENTED
Content-Length: 30
Content-Type: text/html
Date: Tue, 14 Jul 2015 21:22:35 UTC
Server: libonion v0.7.git170.c812b - coralbits.com

&lt;h1&gt;505 - Not implemented&lt;/h1&gt;
</pre>

**Comment by davidmoreno** [comment]
Good eye! Thanks!
