### ISSUE TITLE
poller race condition with O_THREAD will crash onion

### ISSUE THREAD

**Issue by MoZhonghua** [davidmoreno/onion#116]
When start onion with O_THREADED, onion will create multiple threads to poll on the 
single epoll fd. It will cause race condition:
   1. when one thread poll and get a slot, for example, read event of fd 100, and read the data
   2. then another thread poll and get the same slot, because we get more data to read
   3. the first thread decide to remove the slot because of some error, so the slot is gone away now
   4. the second thread try to handle the event, but the slot is removed, and crashed

A solution for this: worker thread should has its own poller, when a connection is established,
the fd is dispatched to a worker thread, the worker thread create slot, process, and delete slot,
nobody else should give a touch to this slot.

**Comment by MoZhonghua** [comment]
Actually, I think a connection MUST always be processed by single worker thread, else it 
always import race conditions.

**Comment by davidmoreno** [comment]
Hi,

thanks very much for the report. Sorry it took me some time to look into it.

The onion/poller.c implementation use EPOLLONESHOT, which ensures no more events will be received until renewing the poller with a new EPOLL_CTL_MOD (http://linux.die.net/man/2/epoll_ctl). This is at https://github.com/davidmoreno/onion/blob/master/src/onion/poller.c#L159  and https://github.com/davidmoreno/onion/blob/master/src/onion/poller.c#L114 . The renewal is at https://github.com/davidmoreno/onion/blob/master/src/onion/poller.c#L458, just after finishing with the request.

Libev and libevent just do something similar internally.

So (unless I miss something) there should be no bug on this.

Regards,
David.

**Comment by MoZhonghua** [comment]
I use onion to handle file upload, when I send request of big file (20M) concurrently, I will always get
this sequence sooner or later:

20150803 01:07:27.939632Z  3697 WARN  ONION poller new slot: 0x7fdd500048f0 - 26 - poller.c:115
20150803 01:07:36.026452Z  3701 WARN  ONION poller delete slot: 0x7fdd500048f0 - 26 - poller.c:127
20150803 01:07:36.181950Z  3698 WARN  ONION poller event in slot: 0x7fdd500048f0 - 1342199360 - poller.c:430

thread 3701 delete slot, but thread 3698 get this slot again. Maybe there is some bug in  my own
code, or maybe there is some subtle corner in poller's implementation. Anyway, I'll figure out it.

**Comment by MoZhonghua** [comment]
Finally, I figured it out. onion_poller_remove() may be called because of timeout, for example:

1. thread A get many slot to process, the last is slot S, so S will wait for a long time to be processed
2. thread B consider this slot S is timeout, delete slot
3. eventually, thread A has processed other slots, and try to process the slot S  and crash

There are some code in onion to deal with this, for example, onion will set event.data.ptr to NULL when timeout,and will set timeout to INT_MAX before processing slot, but this can not eliminate race condition totally.

A temporary solution is set timeout to INT_MAX for ALL pending slots before actually processing any data. This also can not eliminate race condition totally.

**Comment by MoZhonghua** [comment]
IMHO, the only solution is to create a separate poller for each worker thread. Do you have a simpler solution?

**Comment by davidmoreno** [comment]
It should be fixed with merge 3c50142134d480801ad35d61a232c77514cf4c87
