### ISSUE TITLE
dowloading files through onion server

### ISSUE THREAD

**Issue by usergoodvery** [davidmoreno/onion#208]
Hi,
I am just wondering if there is direct built in support for handling  http requests for downloading files? Or is the library user expected to build that layer on top? Can i simply point the library at a file location and have it read it then dispatch the file as a stream to the other end...
regards,

**Comment by davidmoreno** [comment]
There are several options, but on all of them you have to create some code to set up onion and the routes you want to serve.

You can serve a full directory with [`onion_handle_export_local_new`](https://github.com/davidmoreno/onion/blob/master/src/onion/handlers/exportlocal.c#L239), or export a single file with [`onion_shortcut_response_file`](https://github.com/davidmoreno/onion/blob/master/src/onion/shortcuts.c#L139)

The first is a handler, the second a function you can put into your code after some checks (permissions and such) or as a handler.

Anyway, check the examples. There are a couple of file servers that do this, and more.

**Comment by usergoodvery** [comment]
Thanks for that. I may have missed that in the documentation somewhere, but this implementation (onion_shortcut_response_file), especially the way sendfile() is coded, only supports blocking sockets semantics.
