### ISSUE TITLE
LibEv should be called out as a dependency in README

### ISSUE THREAD

**Issue by snej** [davidmoreno/onion#209]
Just cloned the repo to my macOS 10.12.2 system and followed the build instructions, but the `cmake` command fails:
```
...
CMake Error at CMakeModules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find LibEv, try to set the path to LibEv root folder in the
  system variable LIBEV_ROOT_DIR (missing: LIBEV_INCLUDE_DIR LIBEV_LIBRARIES)
Call Stack (most recent call first):
  CMakeModules/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLibEv.cmake:37 (find_package_handle_standard_args)
  src/onion/CMakeLists.txt:27 (find_package)
```
So it looks as though LibEv is a hard dependency, even though this isn't mentioned in the Dependencies section of the README.

Actually I've now looked through the open issues, and Mac support seems to be missing in general. That's unfortunately a deal-breaker for me; we need an HTTP server for a codebase that runs primarily on iOS and Android, secondarily on macOS, MSWindows and Linux. It would be nice if the README had a Compatibility section that listed what platforms it works on.

**Comment by davidmoreno** [comment]
I will try to add a section as suggested, but currenly I have no access to any Apple device (not mac, not iOs), so for me its impossible to ensure compatibility.

Anyway libev is not a 'hard' dependency, as can be replaced by epoll, libevent or kpoll, at compile time.

There is even a branch that I think it is providing this compatibility, but not fully merged yet. If you are interested in giving some love to this branch and we fully merge it, it would be fantastic.

**Comment by snej** [comment]
> Anyway libev is not a 'hard' dependency, as can be replaced by epoll, libevent or kpoll, at compile time.

Well, it sounds like there is a hard dependency on having at least one of those three, so they should be listed as dependencies. (And none of them are installed by default on Apple platforms.)
