### ISSUE TITLE
Can't find a way to parse json arrays

### ISSUE THREAD

**Issue by karakasi** [davidmoreno/onion#220]
Hi!
I would appreciate any pointer for parsing json arrays with libonion. I couldn't find any related example and any method I tried to use failed. It is stated that there might be some limitations but I couldn't find a reference with more details. 
Thanks!

**Comment by davidmoreno** [comment]
Onion has very limited support for JSON. It currently has no support for arrays at all.

If you need proper support for JSON, use another library.

You are also welcome to improve the JSON support at onion (dict.c:726), which should add some way to extract arrays (onion_ptr_list?) from dict values.  But this is a big effort.

Regards, David.

**Comment by karakasi** [comment]
OK that's all I need to know and it is absolutely understandable, keep up the good work!
