### ISSUE TITLE
otemplate mishandles {# template comments #}

### ISSUE THREAD

**Issue by bstarynk** [davidmoreno/onion#224]
Template [comments](https://docs.djangoproject.com/en/dev/ref/templates/language/) are appearing verbatim in the generated C code. 
I expect some `login.thtml` file  starting with 
`{# file login.thtml #}<!DOCTYPE html>`
`{# a template file for Onion's template system#}<html>`
to be expanded into C code without any occurrence of `{#` and with those template comments to disappear.

**Comment by davidmoreno** [comment]
Comments as you detected are not supported.

Pull requests are welcome.

**Comment by bstarynk** [comment]
Please review and accept my commit. Notice the reindentation of files parser.c & parser.h per GNU indentation style.

Feel free to reindent with whatever technology you want
