### ISSUE TITLE
Clarification on license needed.

### ISSUE THREAD

**Issue by SOesterreicher** [davidmoreno/onion#244]
Hello,

I have question regarding the correct licensing of onion in product where we plan a commercial usage.

The webpage https://www.coralbits.com/libonion/ mentions LGPLv3 as license which could be as the license file https://github.com/davidmoreno/onion/blob/master/LICENSE.txt mentions LGPv2+ and Apache which indicates with the + the link to the latest license version.

This is not in line with this page https://github.com/davidmoreno/onion/wiki where the license is GPLv2 and Apache.

I struggle on the LGPLv2+ and Apache in the license file https://github.com/davidmoreno/onion/blob/master/LICENSE.txt. This license information does not clearly indicate the possibility to choose between both licenses. It looks more that both licenses need to be followed.
2 questions:
1.) Is there a possibility to choose the license between LGPLv2+ and Apache ?
2.) If yes how do I indicate this choice in the documentation to the customer in a commercial product?

The indication of the choice is necessary to ensure the Apache license obligations are fulfilled during handover and not the LGPLv2+.

Thanks in advance.
Siegfried Oesterreicher

**Comment by davidmoreno** [comment]
You can choose whatever fits you best.

The LGPL compatibility is required as Apache2 is incompatible with GPL2,
and I want to support both commercial and free software.

**Comment by SOesterreicher** [comment]
Thanks for clarification.
Siegfried Oesterreicher
