### ISSUE TITLE
.mjs suffix should be known for Javascript module files.

### ISSUE THREAD

**Issue by bstarynk** [davidmoreno/onion#247]
The `.mjs`  suffix should be known for JavaScript module files.

Notice that [JavaScript modules are today common to most major browsers](https://developers.google.com/web/fundamentals/primers/modules).

The fix is so trivial that I don't even consider making a formal pull request. It is a one line patch:
```
diff --git a/src/onion/mime.c b/src/onion/mime.c
index 02eb4e8..ea2925b 100644
--- a/src/onion/mime.c
+++ b/src/onion/mime.c
@@ -104,6 +104,7 @@ static void onion_mime_fill() {
     onion_dict_add(onion_mime_dict, "html", "text/html", 0);
     onion_dict_add(onion_mime_dict, "htm", "text/html", 0);
     onion_dict_add(onion_mime_dict, "js", "application/javascript", 0);
+    onion_dict_add(onion_mime_dict, "mjs", "application/javascript", 0);
     onion_dict_add(onion_mime_dict, "css", "text/css", 0);
     onion_dict_add(onion_mime_dict, "png", "image/png", 0);
     onion_dict_add(onion_mime_dict, "jpg", "image/jpeg", 0);

```

**Comment by davidmoreno** [comment]
Updated.

It's impossible to keep up with everything javascript.. I consider myself well informed and never heard before of mjs.

Also added CONTRIBUTORS.md file that was there waiting forever to be added.

Regards,
David.

**Comment by bstarynk** [comment]
Thanks David
