### ISSUE TITLE
Any plans on supporting "SameSite" cookie?

### ISSUE THREAD

**Issue by IronBlood** [davidmoreno/onion#281]
There's an example of `SameSite` attribute on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)

```
Set-Cookie: mykey=myvalue; SameSite=Strict
```

Right now it's still in [draft stage of RFC 6265](https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#rfc.section.4.1.2.7), but most major browsers (except IE) have already support this attribute, according to [MDN's browser compatibility](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite).

I'd like to create a PR if this proposal sounds good to you. Looks like an easy one, with a few more [`onion_response_flags`](https://github.com/davidmoreno/onion/blob/master/src/onion/response.h#L98) and more outputs with [`onion_response_add_cookie`](https://github.com/davidmoreno/onion/blob/master/src/onion/response.c#L638), and of course the [tests](https://github.com/davidmoreno/onion/blob/master/tests/01-internal/03-response.c).

**Comment by davidmoreno** [comment]
Sounds perfect for me. 

The use of the onion_response_flags is, I guess, to force all cookies SameSite. If so, i think that just adding a flag to onion_response_add_cookie would be a perfect first approximation.

**Comment by IronBlood** [comment]
I would like to offer multiple choices as whatever ppl like to use, like:

```c
onion_response_add_cookie(..., OC_HTTP_ONLY | OC_SECURE | OC_SAMESITE_NONE);
// or
onion_response_add_cookie(..., OC_HTTP_ONLY | OC_SECURE | OC_SAMESITE_STRICT);
```

If none of the `OC_SAMESITE_*` flags is used, there'll be no changes to cookies.
