### ISSUE TITLE
License is LGPL v3 on website ?

### ISSUE THREAD

**Issue by gawen** [davidmoreno/onion#87]
Hey guys,

Little issue as I struggled to figure out what was the license of the onion project.

The website indicates "LGPL v3", as it looks like you changed the license with [this commit](https://github.com/davidmoreno/onion/commit/2213af1281f96c62f3ccd8f7824353c04d809911).

So, is the license [ASF + GPLv2](https://github.com/davidmoreno/onion/blob/master/src/onion/http.c#L1-L22) or [LGPL v3](http://www.coralbits.com/libonion/) ?

Thanks for the clarification.

Thank you for the awesome contribution.

**Comment by jeffvandyke** [comment]
Boy, this was a while ago, but <http://www.coralbits.com/libonion/> still says that the license is LGPL v3, and I was a bit nervous until I read this repository's README, so it might still be a good idea to update the website, at least that bit for now.
